//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawGame.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawGame.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ βαλτε σε ολα τα κομματια μια εικονα..
        /// </summary>
        internal static string WheelEditForm_button2_Click_Βαλτε_σε_ολα_τα_κομματια_μια_εικονα {
            get {
                return ResourceManager.GetString("WheelEditForm_button2_Click_Βαλτε_σε_ολα_τα_κομματια_μια_εικονα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ βάλτε το πολύ ένα κομμάτι που χάνει.
        /// </summary>
        internal static string WheelEditForm_button2_Click_Παρακαλώ_βάλτε_το_πολύ_ένα_κομμάτι_που_χάνει {
            get {
                return ResourceManager.GetString("WheelEditForm_button2_Click_Παρακαλώ_βάλτε_το_πολύ_ένα_κομμάτι_που_χάνει", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΠΡΟΣΟΧΗ!.
        /// </summary>
        internal static string WheelEditForm_button2_Click_ΠΡΟΣΟΧΗ {
            get {
                return ResourceManager.GetString("WheelEditForm_button2_Click_ΠΡΟΣΟΧΗ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραφη Πεδιου..
        /// </summary>
        internal static string WheelEditForm_dataGridView1_CellContentClick_Διαγραφη_Πεδιου {
            get {
                return ResourceManager.GetString("WheelEditForm_dataGridView1_CellContentClick_Διαγραφη_Πεδιου", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θελετε να διαγραψετε αυτο το πεδιο οριστικα;.
        /// </summary>
        internal static string WheelEditForm_dataGridView1_CellContentClick_Θελετε_να_διαγραψετε_αυτο_το_πεδιο_οριστικα_ {
            get {
                return ResourceManager.GetString("WheelEditForm_dataGridView1_CellContentClick_Θελετε_να_διαγραψετε_αυτο_το_πεδιο_ο" +
                        "ριστικα_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αυτό το πεδίο δέχεται μόνο νούμερα!.
        /// </summary>
        internal static string WheelEditForm_dataGridView1_CellValidating_Αυτό_το_πεδίο_δέχεται_μόνο_νούμερα {
            get {
                return ResourceManager.GetString("WheelEditForm_dataGridView1_CellValidating_Αυτό_το_πεδίο_δέχεται_μόνο_νούμερα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ βάλτε ένα νούμερο μεγαλύτερο του μηδέν.
        /// </summary>
        internal static string WheelEditForm_dataGridView1_CellValidating_Παρακαλώ_βάλτε_ένα_νούμερο_μεγαλύτερο_του_μηδέν {
            get {
                return ResourceManager.GetString("WheelEditForm_dataGridView1_CellValidating_Παρακαλώ_βάλτε_ένα_νούμερο_μεγαλύτερο_" +
                        "του_μηδέν", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to επιτυχής αποθηκευση!.
        /// </summary>
        internal static string WheelEditForm_OnExit_επιτυχής_αποθηκευση {
            get {
                return ResourceManager.GetString("WheelEditForm_OnExit_επιτυχής_αποθηκευση", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οι αλλαγες που κανατε θα επηρεάσουν την λειτουργία του σερβερ.
        /// Θελετε να κανετε επανεκκινηση τον σερβερ και ολα τα παιχνιδια;.
        /// </summary>
        internal static string WheelEditForm_SaveButton_Click_ {
            get {
                return ResourceManager.GetString("WheelEditForm_SaveButton_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΠΡΟΕΙΔΟΠΟΙΗΣΗ.
        /// </summary>
        internal static string WheelEditForm_SaveButton_Click_ΠΡΟΕΙΔΟΠΟΙΗΣΗ {
            get {
                return ResourceManager.GetString("WheelEditForm_SaveButton_Click_ΠΡΟΕΙΔΟΠΟΙΗΣΗ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εξοδος.
        /// </summary>
        internal static string WheelEditForm_WheelEditForm_FormClosing_Εξοδος {
            get {
                return ResourceManager.GetString("WheelEditForm_WheelEditForm_FormClosing_Εξοδος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θέλετε να αποθηκεύσετε τις αλλαγές που κάνετε;.
        /// </summary>
        internal static string WheelEditForm_WheelEditForm_FormClosing_Θέλετε_να_αποθηκεύσετε_τις_αλλαγές_που_κάνετε_ {
            get {
                return ResourceManager.GetString("WheelEditForm_WheelEditForm_FormClosing_Θέλετε_να_αποθηκεύσετε_τις_αλλαγές_που_κά" +
                        "νετε_", resourceCulture);
            }
        }
    }
}
